### ISSUE TITLE
Create About MSSN page

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#1]
### **Task Overview**

Create the "About MSSN" page

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [ ] All `Click here` buttons will eventually link to the whatsapp dm of the respective leader of the committee
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: Provide links to design files.
  - [Figma Link](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=748-79&t=uZLUUFoYv0JqqHZY-4)
- **Visual Assets**: Attach any images or assets needed.
![ABOUT MSSN OAU](https://github.com/user-attachments/assets/e5fa199a-ee3b-454b-acb1-64a50e0f6a54)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [ ] Design follows figma
- [ ] Mobile responsiveness okay

**Comment by usmahm** [comment]
Done
