### ISSUE TITLE
Create An-Nur Press Pages

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#10]
### **Task Overview**

Create the "An-Nur Press" page

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [ ] Use a mockup data for now, the list will eventually be fetched from the backend when it's ready. Ignore that `Show all` button on the first box for now.
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: Provide links to design files.
  - [Figma Link 1](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=756-186&t=QQSf9wZrQ4THlccR-4)
  - [Figma Link 2](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=758-1157&t=QQSf9wZrQ4THlccR-4)
- **Visual Assets**: Attach any images or assets needed.
 
![AN-NUR PRESS](https://github.com/user-attachments/assets/cfe2dc05-7e6a-4f35-88ee-8e16acf527b0)
![READING ARTICLE](https://github.com/user-attachments/assets/fe17a83d-91ba-4b2c-87c8-169d7a46af28)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [ ] Design follows figma
- [ ] Mobile responsiveness okay

**Comment by Tiskae** [comment]
@usmahm I will like to work on this

**Comment by usmahm** [comment]
Thank you
