### ISSUE TITLE
Create Events Page

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#11]
### **Task Overview**

Create the "Events" page

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [ ] Use a mockup data for now, the list will eventually be fetched from the backend when it's ready. Ignore that `Show all` button on the first box for now.
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: Provide links to design files.
  - [Figma Link](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=820-2034&t=wUzQbuAOiF0xAlfQ-4)
- **Visual Assets**: Attach any images or assets needed.
 
![EVENTS](https://github.com/user-attachments/assets/87e47df9-4175-4bc1-89fa-d278f5b45a8c)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [ ] Design follows figma
- [ ] Mobile responsiveness okay

**Comment by dapoadedire** [comment]
Assign me to this, please.
@usmahm

**Comment by usmahm** [comment]
Thanks @dapoadedire. Please note the comments on the design on figma

**Comment by dapoadedire** [comment]
Okay.
The one about the dynamic page for each event, right?

**Comment by usmahm** [comment]
> Okay. The one about the dynamic page for each event, right?

Yes

**Comment by usmahm** [comment]
What is the update

**Comment by dapoadedire** [comment]
WIP
