### ISSUE TITLE
Create Programs Page

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#12]
### **Task Overview**

Create the "Programs" page

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [ ] Use a mockup data for now, the list will eventually be fetched from the backend when it's ready. Ignore that `Show all` button on the first box for now.
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: Provide links to design files.
  - [Figma Link 1](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=819-367&t=wUzQbuAOiF0xAlfQ-4)
  - [Figma Link 2](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=819-1099&t=wUzQbuAOiF0xAlfQ-4)
- **Visual Assets**: Attach any images or assets needed.
![PROGRAMS](https://github.com/user-attachments/assets/f7a2cc3f-cfca-4786-86d7-deef4f6d4080)

![ACADEMIC PROGRAMS](https://github.com/user-attachments/assets/f128a2cb-9769-4ad5-9cdd-06b3b8b4ec3c)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [ ] Design follows figma
- [ ] Mobile responsiveness okay

**Comment by Tiskae** [comment]
@usmahm please assign this to me

**Comment by usmahm** [comment]
Thank you
