### ISSUE TITLE
Create About MSSN Excos

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#3]
### **Task Overview**

Create the "About MSSN" page

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [ ] Use a mockup data for now, the list will eventually be fetched from the backend when it's ready. Ignore that `Show all` button on the first box for now.
  - [ ] The meet our past executives button at the bottom should lead to the same page but appended with  `/{year}`. Use the same design but in the header, add `- {year} session`.
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: Provide links to design files.
  - [Figma Link](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=748-483&t=uZLUUFoYv0JqqHZY-4)
- **Visual Assets**: Attach any images or assets needed.
 
![MSSN OAU EXCOS](https://github.com/user-attachments/assets/c236f010-3792-4fee-b0ba-2f1211bc9faf)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [ ] Design follows figma
- [ ] Mobile responsiveness okay

**Comment by usmahm** [comment]
Done
