### ISSUE TITLE
Create About Staff Advisers Page

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#4]
### **Task Overview**

Create the "About Staff Advisers" page

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [x] Use mockup data for now, list will be fetched from backend eventually.
  - [ ] All buttons should do what they are expected to do.
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: 
  - [Figma Link](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=749-2041&t=uZLUUFoYv0JqqHZY-4)
- **Visual Assets**: Attach any images or assets needed.
![STAFF ADVISERS](https://github.com/user-attachments/assets/a0865e43-93ca-44ac-ac4c-56cd92a92b77)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [x] Design follows figma
- [x] Mobile responsiveness okay

**Comment by usmahm** [comment]
Done
