### ISSUE TITLE
Create Donate Page

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#5]
### **Task Overview**

Create the "Donate" `/donate` page

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [ ] Just UI for now
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: Provide links to design files.
  - [Figma Link](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=760-372&t=uZLUUFoYv0JqqHZY-4)
- **Visual Assets**: Attach any images or assets needed.
![DONATE](https://github.com/user-attachments/assets/78acc1c9-a171-407c-a94c-8e3bdd109561)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [ ] Design follows figma
- [ ] Mobile responsiveness okay

**Comment by dapoadedire** [comment]
I'll work on this issue

**Comment by usmahm** [comment]
Thanks @dapoadedire

**Comment by usmahm** [comment]
@dapoadedire  You can use this component for that header https://github.com/MSSNOAU/frontend/tree/main/src/components/UIUnits/PageHeader
