### ISSUE TITLE
Create Prayer Times Pages

### ISSUE THREAD

**Issue by usmahm** [MSSNOAU/frontend#6]
### **Task Overview**

Create the "Prayer Times" - `/prayer-times` and "Full Prayer Times" pages

### **Technical Notes**

- **Branching**: Kindly create a new branch from `development` for this task.
- **Branch Naming**: Kindly follow this pattern  `feat-{issue-number}` for new features and `fix-{issue-number}` for bug fix.
- **Merging**: Kindly make a pull request to `development` when you are done.
- The `Subscribe To An-Nur Press Blog` box can be reused, check landing page.

### **Requirements**

- **Functionality**: List of functionalities that need to be implemented.
  - [ ] `See full timetable` button should lead to the Full prayer times page
- **Responsiveness**: Should be responsive across different devices? I currently have a `responsive_mb` mixin that can be used.

### **Design References**

- **Mockups/Wireframes**: Provide links to design files.
  - [Figma Link 1](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=855-590&t=uZLUUFoYv0JqqHZY-4)
  - [Figma Link 2](https://www.figma.com/design/Xnp3UT8BhcJkuU1WaOpukM/MSSNOAU?node-id=867-1552&t=uZLUUFoYv0JqqHZY-4)
- **Visual Assets**: Attach any images or assets needed.
![PRAYER TIMES](https://github.com/user-attachments/assets/cf637f4f-c407-4a8e-ae18-c68fc0acb7e8)

![AWO HALL MOSQUE PRAYER TIMES](https://github.com/user-attachments/assets/1b1a1359-a879-4270-afaf-177ffeccd5b4)

- **Style Guidelines**: Kindly reuse already created components where possible, and create reusable components where possible. Thanks

### **Acceptance Criteria**

- [ ] Design follows figma
- [ ] Mobile responsiveness okay

**Comment by Hussein-miracle** [comment]
@usmahm i'm looking to work on this

**Comment by usmahm** [comment]
Thank you @Hussein-miracle

**Comment by usmahm** [comment]
@Hussein-miracle you can use this component for that header https://github.com/MSSNOAU/frontend/tree/main/src/components/UIUnits/PageHeader

**Comment by usmahm** [comment]
@Hussein-miracle please what is the update on this boss

**Comment by Hussein-miracle** [comment]
Now done
